/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ['./App.{js,ts,tsx}', './app/**/*.{js,ts,tsx}', './components/**/*.{js,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#ffdad6",
        "on-tertiary-container": "#6c4d01",
        "outline": "#8e909a",
        "surface-container-lowest": "#0d0e11",
        "on-surface-variant": "#c4c6d0",
        "on-background": "#e3e2e7",
        "on-secondary-fixed-variant": "#004f54",
        "surface-variant": "#343538",
        "outline-variant": "#44474f",
        "on-tertiary-fixed-variant": "#5d4200",
        "inverse-on-surface": "#2f3034",
        "light-surface": "#f8f9fc",
        "primary-fixed-dim": "#adc6ff",
        "surface-container-highest": "#343538",
        "light-surface-container": "#eceff4",
        "tertiary-fixed-dim": "#ebc06e",
        "on-secondary-fixed": "#002022",
        "tertiary": "#ffdea4",
        "tertiary-fixed": "#ffdea5",
        "on-tertiary": "#412d00",
        "on-secondary-container": "#006a70",
        "secondary-container": "#00f1fe",
        "secondary": "#ddfcff",
        "on-error": "#690005",
        "surface-container": "#1e1f23",
        "tertiary-container": "#ebc06e",
        "surface-container-low": "#1a1b1f",
        "primary-fixed": "#d8e2ff",
        "primary-container": "#adc6ff",
        "on-tertiary-fixed": "#261900",
        "primary": "#d8e2ff",
        "surface-dim": "#121317",
        "error": "#ffb4ab",
        "on-secondary": "#00363a",
        "on-primary-fixed-variant": "#2c4677",
        "performance-magenta": "#ffb4ab",
        "neon-lime": "#94db00",
        "error-container": "#93000a",
        "light-on-surface": "#10141a",
        "secondary-fixed": "#74f5ff",
        "on-primary-fixed": "#001a42",
        "background": "#121317",
        "on-primary": "#122f5f",
        "surface-tint": "#adc6ff",
        "inverse-primary": "#455e90",
        "secondary-fixed-dim": "#00dbe7",
        "surface-container-high": "#292a2d",
        "surface-bright": "#38393d",
        "on-primary-container": "#385283",
        "on-surface": "#e3e2e7",
        "inverse-surface": "#e3e2e7",
        "surface": "#121317"
      },
      fontFamily: {
        "sora": ["Sora_400Regular", "Sora_600SemiBold", "Sora_700Bold", "Sora_800ExtraBold"],
        "hanken": ["HankenGrotesk_400Regular", "HankenGrotesk_600SemiBold"],
        "jetbrains": ["JetBrainsMono_400Regular", "JetBrainsMono_700Bold"],
      },
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "40px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
      }
    },
  },
  plugins: [],
};
